import { randomString } from "./string";

export const users = [
  {
    _id: "1",
    name: "uc",
    email: "asdf@da.com",
    role: "emp",
    avatar: "",
  },
  {
    _id: "2",
    name: "uc",
    email: "asd2f@da.com",
    role: "emp",
    avatar: "",
  },
  {
    _id: 3,
    name: "uc",
    email: "assdf@da.com",
    role: "emp",
    avatar: "",
  },
  {
    _id: 4,
    name: "uc",
    email: "asddf@da.com",
    role: "emp",
    avatar: "",
  },
  {
    _id: randomString(),
    name: "uc",
    email: "adsdf@da.com",
    role: "emp",
    avatar: "",
  },
  {
    _id: randomString(),
    name: "uc",
    email: "qasdf@da.com",
    role: "emp",
    avatar: "",
  },
  {
    _id: randomString(),
    name: "uc",
    email: "sasdf@da.com",
    role: "emp",
    avatar: "",
  },
];

export const packages = [
  {
    _id: "1",
    images: ["img1.png", "img2.png"],
    customer: {
      prefix: "customer",
      id: "customer",
    },
    trackingNumber: "20230120128932",
    date: "2023-10-18 10:10:10",
    package: {
      width: 30,
      length: 30,
      height: 30,
      weight: 30,
    },
    status: "New",
    staff: "N/A",
    createdAt: "2023-10-17",
    updatedAt: "2023-10-17",
    chat: [
      {
        from: {
          _id: "1",
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: "2",
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: "1",
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: "2",
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: "2",
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: "1",
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
    ],
  },
  {
    _id: randomString(),
    images: ["img1.png", "img2.png"],
    customer: {
      prefix: "customer",
      id: "customer",
    },
    trackingNumber: "20230120128932",
    date: "2023-10-18 10:10:10",
    package: {
      width: 30,
      length: 30,
      height: 30,
      weight: 30,
    },
    status: "New",
    staff: "N/A",
    createdAt: "2023-10-17",
    updatedAt: "2023-10-17",
    chat: [
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
    ],
  },
  {
    _id: randomString(),
    images: ["img1.png", "img2.png"],
    customer: {
      prefix: "customer",
      id: "customer",
    },
    trackingNumber: "20230120128932",
    date: "2023-10-18 10:10:10",
    package: {
      width: 30,
      length: 30,
      height: 30,
      weight: 30,
    },
    status: "New",
    staff: "N/A",
    createdAt: "2023-10-17",
    updatedAt: "2023-10-17",
    chat: [
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
    ],
  },
  {
    _id: randomString(),
    images: ["img1.png", "img2.png"],
    customer: {
      prefix: "customer",
      id: "customer",
    },
    trackingNumber: "20230120128932",
    date: "2023-10-18 10:10:10",
    package: {
      width: 30,
      length: 30,
      height: 30,
      weight: 30,
    },
    status: "New",
    staff: "N/A",
    createdAt: "2023-10-17",
    updatedAt: "2023-10-17",
    chat: [
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
    ],
  },
  {
    _id: randomString(),
    images: ["img1.png", "img2.png"],
    customer: {
      prefix: "customer",
      id: "customer",
    },
    trackingNumber: "20230120128932",
    date: "2023-10-18 10:10:10",
    package: {
      width: 30,
      length: 30,
      height: 30,
      weight: 30,
    },
    status: "New",
    staff: "N/A",
    createdAt: "2023-10-17",
    updatedAt: "2023-10-17",
    chat: [
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
    ],
  },
  {
    _id: randomString(),
    images: ["img1.png", "img2.png"],
    customer: {
      prefix: "customer",
      id: "customer",
    },
    trackingNumber: "20230120128932",
    date: "2023-10-18 10:10:10",
    package: {
      width: 30,
      length: 30,
      height: 30,
      weight: 30,
    },
    status: "New",
    staff: "N/A",
    createdAt: "2023-10-17",
    updatedAt: "2023-10-17",
    chat: [
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
      {
        from: {
          _id: randomString(),
          name: "UC",
          email: "asd@asd.com",
          avatar: "",
        },
        to: {
          _id: randomString(),
          name: "UC",
          email: "adsf@swe.sdf",
          avatar: "",
        },
        msg: "this is message",
        date: "2023-10-18 10:10:10",
      },
    ],
  },
];
